### ISSUE TITLE
Bigdata con dati storici

### ISSUE THREAD

**Issue by d4rkstar** [fantacalcio/fantacalcio#12]

**Comment by d4rkstar** [comment]
https://github.com/openfootball/italy

**Comment by FrankMaverick** [comment]
L'avevo visto anche io, ma sembra non aggiornato. Ad esempio [2022-23](https://github.com/openfootball/italy/tree/master/2022-23) non ci sono i risultati, c'è solo il calendario.
Una possibile alternativa potrebbe essere wikipedia, esempio [2022-2023](https://it.wikipedia.org/wiki/Serie_A_2022-2023). Qui ci sono anche altre statistiche.

**Comment by AntonioPiga** [comment]
Anche se non troviamo tutti i dati da una sola fonte, potrebbe non essre un problema. Comunque Wikipedia effettivamente è perfetto @FrankMaverick .

**Comment by AntonioPiga** [comment]
inoltre ho visto anche loro, magari è conveniente ma non hanno un pricing pubblico: https://api.besoccer.com

**Comment by FrankMaverick** [comment]
Altri dataset che sembrano interessanti:

**transfermarkt-datasets (Football (Soccer) data scraped from Transfermarkt website)**
https://www.kaggle.com/datasets/davidcariboo/player-scores/data
https://github.com/dcaribou/transfermarkt-datasets

**International football results from 1872 to today**
https://www.kaggle.com/datasets/patateriedata/all-international-football-results

**r/Soccer Posts & Comments**
Discover the best of r/Soccer: Engaging Posts & Insightful Comments
https://www.kaggle.com/datasets/curiel/rtiktokcringe-posts-and-comments

**Football Data | Top 5 European Leagues**
More than 110,000 match stats from top football leagues across Europe
https://www.kaggle.com/datasets/prateekchauhands/football-data-top-5-european-leagues
