### ISSUE TITLE
UI: Inserire i contenuti nello slider

### ISSUE THREAD

**Issue by AntonioPiga** [fantacalcio/fantacalcio#24]
dal branch feature/new-ui elaborare i contenuti dello slider in questo ordine:

Nel componente HeroSlider.svelte andrà mappato per ognuno dei seguenti elementi, questo body:

constData = {
    title;
    description;
    buttonLabel;
    buttonOnClick; // si aspetta un metodo, es.  () => console.log -> in questi casi facciamo uno scroll alla 
    funzione (es lista calciatori va sulla tabella dei players)
    imageUrl; 
    imageAlt; // descrizione immagini per seo
}

1. Lista calciatori
2. AIrticoli
3. Probabili formazioni

**Comment by IvanDF** [comment]
@claudiomanno 

![Image](https://github.com/fantacalcio/fantacalcio/assets/70886693/8ec04079-3369-4ea1-a34f-2b920bf9f8ff)

https://www.figma.com/design/87yfjJVoERblDv6TS0slao/FantaAICalcio?node-id=358-696&t=dAWXiwK3OTNilFxV-0
