### ISSUE TITLE
Usare la cache per storare i dati di current_serie_a_players

### ISSUE THREAD

**Issue by AntonioPiga** [fantacalcio/fantacalcio#29]
per l'endpoint: db/main?model=player&current_serie_a_players=true che si trova sotto packages/db/main/models/player.py 

storare il dato nella cache redis (se non è già stato storato)-> svuotare la cache una volta al giorno
per vedere i parametri per collegarsi a redis usare nuv -config -d 

NB: loggarsi con l'utente fantatest

**Comment by FrankMaverick** [comment]
@antdlc135 se puoi fare un check perché mi sembra che ci sia qualcosa che non va sulla cache. Sembra che il timer non scade mai e/o il valore in cache rimane per un tempo indefinito.

Inoltre, per questo metodo get_all_current_serie_a_players e altri simili che vengono usati in ETL (Nelle cui note c'è scritto 'Crucial for ETL process'), meglio non mettere la cache. Quindi in questo caso va eliminata.

Grazie

**Comment by antdlc135** [comment]
ciao @FrankMaverick verifico; grazie per la segnalazione.

**Comment by FrankMaverick** [comment]
figurati @antdlc135 ;) 
questo metodo get_all_current_serie_a_players l'ho fixato io. Ho eliminato la cache perché usato in etl.

A presto ;)

**Comment by antdlc135** [comment]
ciao @FrankMaverick come stai? :D

ho fatto un test con l'utenza "fantatest", senza modificare l'attuale implementazione della cache.

A scopo di debug ho portato expiration time a 60 secondi, e dal poll dei log (vedi img) il comportamento delle logiche è andato come previsto.

Puoi descrivermi il caso di test dal quale è risultato che la cache non si cancellasse alla scadenza dell'expiration time?

PS. considera che al momento, as-is, è stato impostato un expiration time di default di 86400 secondi (pati a 24h)

Fammi sapere;

grazie sempre ed a presto! :)

![Image](https://github.com/user-attachments/assets/9fe556a6-19dd-4374-8ca0-11c8fa25ea6e)

**Comment by FrankMaverick** [comment]
Ciao @antdlc135

ora non ricordo con precisioni, ma dai test di luglio, aggiornando i player, la query get_current_serie_a_players mi dava sempre gli stessi risultati in cache. Disattivando la cache, invece, mi dava i nuovi risultati.

Comunque la settimana scorsa ho fatto qualche piccola modifica (c'è una PR) e ho anche inserito qualche info in più sul log relativo al TTL (quindi ai secondi mancanti per lo svuotamento della cache). Ora dovrebbe essere tutto ok.
Inoltre, ho aggiunto un metodo per svuotare la cache, utile in seguito all'esecuzione dell'ETL.

A presto ;)
