### ISSUE TITLE
Calcolo del rating mediante algoritmo di ML

### ISSUE THREAD

**Issue by FrankMaverick** [fantacalcio/fantacalcio#43]
Sviluppare un modello di Machine Learning per il calcolo del valore di `rating_target` utilizzando i dati presenti nel file CSV, che contiene variabili legate alle statistiche dei giocatori durante una partita, il risultato della partita e altre info utili. 
Tra le variabili di input c'è anche il `rating` fornito dal provider, che però tende a essere più alto e a volte si discosta molto dal target. 

File CSV: [rating_stats.csv](https://github.com/user-attachments/files/17421479/rating_stats.csv)

**Comment by AntonioPiga** [comment]
@FrankMaverick sentiti con Dario Tramontin :D

**Comment by FrankMaverick** [comment]
prima versione: 
https://github.com/FrankMaverick/fantacalcio-rating-optimizer
