### ISSUE TITLE
Dentro il db di fantacalcio (mastrogpt repo), mostrare anche la column fbrating nelle query che riguardano fixture stats

### ISSUE THREAD

**Issue by AntonioPiga** [fantacalcio/fantacalcio#47]
Eliminare il rating che ci manda apifotoball dagli endpoint che riguardano il frontend e il bot.
Inserire invece fbrating. L'impatto è sulle domande del bot tipo: 

- "cosa ha fatto leao nell'ultima in casa?"
- "cosa ha fatto leao nelle ultime 3?"
- "cosa ha fatto leao nella scorsa partita?"
- "cosa ha fatto leao nella seconda giornata?"
- "chi sono stati i migliori attaccanti nell'ultima giornata?"

**Comment by francesco-cardinale** [comment]
@AntonioPiga questo è fatto, solo che ci sono dei fix da fare che riguardano altre cose, es.
- https://github.com/fantacalcio/fantacalcio/issues/32#issuecomment-2543048886
- Il bot non da quasi mai il rating nelle risposte, quindi forse va istruito per fare sia il voto che il fantavoto (ci sono entrambi)
- Manca per ora il dato aggregato https://github.com/fantacalcio/scraping-engine/issues/74
