### ISSUE TITLE
Passare il rating come balun_rating come rating e il fanta rating come fanta_balun_rating

### ISSUE THREAD

**Issue by AntonioPiga** [fantacalcio/fantacalcio#48]

**Comment by francesco-cardinale** [comment]
positive_weights = {
            'goals_total': 3,        # Gol +3
            'goals_assists': 1,      # Assist +1
            'penalty_saved': 3,      # Rigore parato +3
            'penalty_won': 1         # Rigore guadagnato +1
        }
		
negative_weights = {
            'penalty_missed': -3,    # Rigore sbagliato -3
            'goals_conceded': -1,    # Gol subito -1
            'penalty_committed': -1, # Rigore causato -1
            'cards_red': -1,         # Espulsione -1
            'cards_yellow': -0.5     # Ammonizione -0.5
        }
		
DOPPIO GIALLO : tot -1

**Comment by francesco-cardinale** [comment]
i campi (fbrating e fantarating) sono presenti a db (in fixture players statistics) e valorizzati con etl
è necessario solo calcolare i campi aggregati per salvarli n player statistics
