### ISSUE TITLE
Raccolta requisiti

### ISSUE THREAD

**Issue by AntonioPiga** [fantacalcio/fantacalcio#5]

**Comment by alesscap** [comment]
# Requisiti funzionali
Elenco delle funzionalità che l'applicativo deve avere.
Brainstorming: 
* quali i desiderata principali di un giocatore di fantacalcio?
* esistono gia' strumenti simili sul mercato? che limiti hanno?
* definizione ruoli utente
* intefacce con applicativi esterni (fantamaster poi??) 
* interfacce interne
* storage?
# Funzionalità AI assisted
* Opinionisti AI based? (mettendo a confronto LLM diversi?)
* Accesso a dati aggiornati partita per partita (RAG based?)
# UX/UI
# Requisiti non funzionali
