### ISSUE TITLE
Palette Grafica

### ISSUE THREAD

**Issue by AntonioPiga** [fantacalcio/fantacalcio#7]

**Comment by FrankMaverick** [comment]
Alcune idee:
https://coolors.co/0d0a0b-454955-f3eff5-72b01d-3f7d20
https://coolors.co/2b2d42-8d99ae-ffffff-33ffaa-054d6e
https://coolors.co/00f981-33ffaa-ffffff-000000

**Comment by AntonioPiga** [comment]
@IvanDF se vuoi dai uno sguardo!

**Comment by IvanDF** [comment]
Ho dato un occhiata alle varie palette di colori, ho avuto modo di creare alcune combinazioni alternative. Qui di seguito, qualche idea facendo anche delle prove riguardanti i contrasti dei colori e la leggibilità:

Palette 1:
![Image](https://github.com/fantacalcio/fantacalcio/assets/70886693/004b6d8d-1dd5-4297-a9ba-c18b4cf9fa8f)
La palette presenta colori simili a pastello

Palette 2:
![Image](https://github.com/fantacalcio/fantacalcio/assets/70886693/f5430e4c-b6be-4d96-b182-4263fda5b629)
La palette presenta colori più accesi

Palette 3:
![Image](https://github.com/fantacalcio/fantacalcio/assets/70886693/16c7d0f3-4c8c-4c46-8d66-c12f54c7ee66)
La palette presenta colori più accesi
