### ISSUE TITLE
Scouting nuove API da integrare fuori da Fantamaster

### ISSUE THREAD

**Issue by AntonioPiga** [fantacalcio/fantacalcio#8]

**Comment by d4rkstar** [comment]
Ad un primo giro ho trovato queste: https://rapidapi.com/cantagalloedoardo/api/serie-a2

Nel piano Basic hanno dei limiti, ma sono gratuite

**Comment by d4rkstar** [comment]
Anche questa è molto "quotata", ma si paga: https://www.sportmonks.com/football-api/serie-a-api/

**Comment by AntonioPiga** [comment]
Ho visto anche questo @d4rkstar , non se se possa aver senso prendere spunto : https://github.com/ali-sheiba/opta_sd 
e poi https://www.api-football.com/pricing fanno da ponte per rapid api, mettendo qualche opzione conveniente

**Comment by FrankMaverick** [comment]
Probabilmente [StatsPerform](https://www.statsperform.com/) pure si può considerare (magari in ottica futura).
I costi non sono descritti, ma è l'azienda che ha acquisito Opta e da cui si riforniscono praticamente tutti.

Oltre a dati storici e in tempo reale, offre anche **Predictive Data**
_Our predictive data, built on our unrivaled data collection and powered by our sports-AI team, predicts likely **match outcomes and **player performance****_
